name: Build and Deploy Web + APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Build Web
      - name: Build web app
        run: flutter build web --base-href="/kg-classroom/" --release

      # Build APK
      - name: Build Android APK
        run: flutter build apk --release

      # Deploy web to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_PAGE_TOKEN }}
          publish_dir: build/web

      # Upload APK as GitHub artifact
      - name: Upload APK to GitHub as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kg-classroom-apk
          path: build/app/outputs/flutter-apk/app-release.apk
